### ISSUE TITLE
Nothing written about setting up public keys

### ISSUE THREAD

**Issue by eric-hendrickson** [mkdecisiondev/devdocs#16]
We need someone to write an article on setting up SSH keys

**Comment by msssk** [comment]
Do we? For what purposes?

I've only used them with Git previously, and some releases ago it became irrelevant.

**Comment by eric-hendrickson** [comment]
If you have 2FA configured, you do need them. At least that was the issue that the new batch of TFEs faced this morning

**Comment by msssk** [comment]
Added in 988ae89. Please close this issue if the addition looks good to you.

**Comment by eric-hendrickson** [comment]
Resolved #16
