### ISSUE TITLE
PR 2 defects

### ISSUE THREAD

**Issue by msssk** [mkdecisiondev/devdocs#7]
PR 2 has numerous defects that need to be addressed:
https://github.com/mkdecisiondev/devdocs/pull/2#pullrequestreview-97956804

Also, curly quotes are an abomination and should be avoided. It's not a big enough issue to request changes in the PR, but for the future don't use them.

There are numerous paragraphs of instructions that say "do this then this then this". It's easier to understand and follow things like this presented as lists. Prefer bulleted lists for groups of related concepts, numbered lists for sequential steps.

I did not review this PR in 100% detail - please read the feedback and apply anywhere else it's relevant, even if I haven't specifically noted it.

**Comment by eric-hendrickson** [comment]
Curly quotes are a residual from using Google docs to do our documentation. Apart from that, we'll take a look.

**Comment by eric-hendrickson** [comment]
Resolved #7
